type CategoryProduct = {
  id: string;
  title: string;
  price?: string;
  sizes?: string[];
  tag: string;
  image: string;
};

type CategoryPage = {
  title: string;
  intro: string;
  heroImage: string;
  products: CategoryProduct[];
};

const ML = ["M", "L"];
const ONE_SIZE = ["One Size"];

export const womenCategoryPages: Record<string, CategoryPage> = {
  dresses: {
    title: "Dresses",
    intro: "Elegant silhouettes for events, worship, and standout occasions.",
    heroImage: "/images/women/dresses.png",
    products: [
      {
        id: "wd2",
        title: "Blue Denim Jumpsuit",
        price: "$35",
        sizes: ML,
        tag: "Dress",
        image: "/images/products/Outfit_Styles_002.jpeg",
      },
      {
        id: "wd4",
        title: "Casual Black Side Pocket Jumpsuit",
        price: "$35",
        sizes: ML,
        tag: "Dress",
        image: "/images/products/Outfit_Styles_004.jpeg",
      },
      {
        id: "wd5",
        title: "2 Piece Orange Set",
        price: "$45",
        sizes: ML,
        tag: "Set",
        image: "/images/products/Outfit_Styles_005.jpeg",
      },
      {
        id: "wd6",
        title: "2 Piece Green/Blue Skirt Set",
        price: "$45",
        sizes: ML,
        tag: "Set",
        image: "/images/products/Outfit_Styles_006.jpeg",
      },
      {
        id: "wd7",
        title: "2 Piece White/Multicolor Pant Set",
        sizes: ML,
        tag: "Set",
        image: "/images/products/Outfit_Styles_007.jpeg",
      },
      {
        id: "wd8",
        title: "Off Shoulder Multicolor Dress",
        price: "$60",
        sizes: ML,
        tag: "Dress",
        image: "/images/products/Outfit_Styles_008.jpeg",
      },
      {
        id: "wd9",
        title: "2 Piece Green/Blue Skirt Set",
        price: "$45",
        sizes: ML,
        tag: "Set",
        image: "/images/products/Outfit_Styles_009.jpeg",
      },
      {
        id: "wd12",
        title: "Casual Dress",
        price: "$35",
        sizes: ML,
        tag: "Dress",
        image: "/images/products/Outfit_Styles_012.jpeg",
      },
      {
        id: "wd18",
        title: "Amy Green Casual Jumpsuit",
        price: "$50",
        sizes: ML,
        tag: "Dress",
        image: "/images/products/Outfit_Styles_018.jpeg",
      },
      {
        id: "wd19",
        title: "Oxblood Dress to Impress",
        price: "$55",
        sizes: ML,
        tag: "Dress",
        image: "/images/products/Outfit_Styles_019.jpeg",
      },
      {
        id: "wd20",
        title: "Dress to Impress Casual",
        price: "$40",
        sizes: ML,
        tag: "Dress",
        image: "/images/products/Outfit_Styles_020.jpeg",
      },
      {
        id: "wd21",
        title: "Red 2 Set Pant",
        price: "$55",
        sizes: ML,
        tag: "Set",
        image: "/images/products/Outfit_Styles_021.jpeg",
      },
      {
        id: "wd24",
        title: "Muffled Dress to Impress",
        price: "$65",
        sizes: ML,
        tag: "Dress",
        image: "/images/products/Outfit_Styles_024.jpeg",
      },
      {
        id: "wd25",
        title: "Sparkle Blue Dress",
        price: "$70",
        sizes: ML,
        tag: "Dress",
        image: "/images/products/Outfit_Styles_025.jpeg",
      },
      {
        id: "wd26",
        title: "Brown Dress to Impress",
        price: "$75",
        sizes: ML,
        tag: "Dress",
        image: "/images/products/Outfit_Styles_026.jpeg",
      },
      {
        id: "wd27",
        title: "Dress to Party",
        price: "$75",
        sizes: ML,
        tag: "Party",
        image: "/images/products/Outfit_Styles_027.jpeg",
      },
      {
        id: "wd28",
        title: "Off Shoulder Dress to Party",
        price: "$77",
        sizes: ML,
        tag: "Party",
        image: "/images/products/Outfit_Styles_028.jpeg",
      },
      {
        id: "wd34",
        title: "Cross Shoulder Dress to Impress",
        price: "$45",
        sizes: ML,
        tag: "Dress",
        image: "/images/products/Outfit_Styles_034.jpeg",
      },
      {
        id: "wd35",
        title: "Knockout Jacket",
        price: "$55",
        sizes: ML,
        tag: "Jacket",
        image: "/images/products/Outfit_Styles_035.jpeg",
      },
      {
        id: "wd36",
        title: "Knockout Jacket",
        price: "$55",
        sizes: ML,
        tag: "Jacket",
        image: "/images/products/Outfit_Styles_036.jpeg",
      },
      {
        id: "wd43",
        title: "Black Body-hug Set",
        price: "$40",
        sizes: ML,
        tag: "Set",
        image: "/images/products/Outfit_Styles_043.jpeg",
      },
      {
        id: "wd44",
        title: "Mini Electrifying Party Dress",
        price: "$55",
        sizes: ML,
        tag: "Party",
        image: "/images/products/Outfit_Styles_044.jpeg",
      },
      {
        id: "wd45",
        title: "Mini Electrifying Party Dress",
        price: "$55",
        sizes: ML,
        tag: "Party",
        image: "/images/products/Outfit_Styles_045.jpeg",
      },
      {
        id: "wd46",
        title: "Frontal Slit Casual Dress",
        price: "$45",
        sizes: ML,
        tag: "Dress",
        image: "/images/products/Outfit_Styles_046.jpeg",
      },
      {
        id: "wd47",
        title: "Frontal Slit Casual Dress",
        price: "$45",
        sizes: ML,
        tag: "Dress",
        image: "/images/products/Outfit_Styles_047.jpeg",
      },
      {
        id: "wd50",
        title: "2 Color Open Jacket",
        price: "$40",
        sizes: ML,
        tag: "Jacket",
        image: "/images/products/Outfit_Styles_050.jpeg",
      },
      {
        id: "wd51",
        title: "Frontal Slit Casual Dress",
        price: "$45",
        sizes: ML,
        tag: "Dress",
        image: "/images/products/Outfit_Styles_051.jpeg",
      },
      {
        id: "wd57",
        title: "African Black/Gold Dress",
        price: "$80",
        sizes: ONE_SIZE,
        tag: "African",
        image: "/images/products/Outfit_Styles_057.jpeg",
      },
      {
        id: "wd59",
        title: "2 Side Pocket Red African Dress",
        price: "$80",
        sizes: ONE_SIZE,
        tag: "African",
        image: "/images/products/Outfit_Styles_059.jpeg",
      },
      {
        id: "wd60",
        title: "2 Side Pocket Yellow African Dress",
        price: "$80",
        sizes: ONE_SIZE,
        tag: "African",
        image: "/images/products/Outfit_Styles_060.jpeg",
      },
      {
        id: "wd61",
        title: "2 Side Pocket Multicolor African Dress",
        price: "$80",
        sizes: ONE_SIZE,
        tag: "African",
        image: "/images/products/Outfit_Styles_061.jpeg",
      },
      {
        id: "wd62",
        title: "2 Side Pocket Multicolor African Dress",
        price: "$80",
        sizes: ONE_SIZE,
        tag: "African",
        image: "/images/products/Outfit_Styles_062.jpeg",
      },
      {
        id: "wd65",
        title: "2 Set Top/Short Casual",
        price: "$55",
        sizes: ML,
        tag: "Set",
        image: "/images/products/Outfit_Styles_065.jpeg",
      },
      {
        id: "wd66",
        title: "African Embroidered Jacket",
        price: "$110",
        sizes: ONE_SIZE,
        tag: "African",
        image: "/images/products/Outfit_Styles_066.jpeg",
      },

      // NEW FEATURED DRESSES
      {
        id: "wd-blue-party-long",
        title: "Blue Party Long Dress",
        price: "$85",
        sizes: ML,
        tag: "Party",
        image: "/images/products/blue-party-long-dress.jpg",
      },
      {
        id: "wd-antique-gold",
        title: "Antique Gold Dress",
        price: "$90",
        sizes: ML,
        tag: "Featured",
        image: "/images/products/antique-gold-dress.jpg",
      },
      {
        id: "wd-metallic-party",
        title: "Metallic Party Dress",
        price: "$110",
        sizes: ML,
        tag: "Featured",
        image: "/images/products/metallic-party-dress.jpg",
      },
      {
        id: "wd-party-silver-stone",
        title: "Party Silver Stone Party Dress",
        price: "$75",
        sizes: ML,
        tag: "Party",
        image: "/images/products/party-silver-stone-party-dress.jpg",
      },
      {
        id: "wd-party-gold-stone",
        title: "Party Gold Stone Party Dress",
        price: "$75",
        sizes: ML,
        tag: "Party",
        image: "/images/products/party-gold-stone-dress.jpg",
      },
    ],
  },

  sets: {
    title: "Sets",
    intro: "Polished coordinated looks with modern elegance and strong structure.",
    heroImage: "/images/women/sets.png",
    products: [
      {
        id: "ws1",
        title: "Red Off Shoulder Jumpsuit",
        price: "$80",
        sizes: ML,
        tag: "Set",
        image: "/images/products/Outfit_Styles_001.jpeg",
      },
      {
        id: "ws10",
        title: "Amy Green Jumpsuit",
        price: "$80",
        sizes: ML,
        tag: "Set",
        image: "/images/products/Outfit_Styles_010.jpeg",
      },
      {
        id: "ws14",
        title: "Black/White Dress to Impress Set",
        price: "$75",
        sizes: ML,
        tag: "Set",
        image: "/images/products/Outfit_Styles_014.jpeg",
      },
      {
        id: "ws15",
        title: "Off Shoulder Jumpsuit",
        price: "$65",
        sizes: ML,
        tag: "Set",
        image: "/images/products/Outfit_Styles_015.jpeg",
      },
      {
        id: "ws16",
        title: "Black/White Casual Set",
        price: "$65",
        sizes: ML,
        tag: "Set",
        image: "/images/products/Outfit_Styles_016.jpeg",
      },
      {
        id: "ws17",
        title: "Short Blue Jumpsuit",
        price: "$65",
        sizes: ML,
        tag: "Set",
        image: "/images/products/Outfit_Styles_017.jpeg",
      },
      {
        id: "ws22",
        title: "Off Shoulder White Jumpsuit",
        price: "$75",
        sizes: ML,
        tag: "Set",
        image: "/images/products/Outfit_Styles_022.jpeg",
      },
      {
        id: "ws23",
        title: "Dress to Impress Black Jumpsuit",
        price: "$75",
        sizes: ML,
        tag: "Set",
        image: "/images/products/Outfit_Styles_023.jpeg",
      },
      {
        id: "ws37",
        title: "Brown Outing Jacket",
        price: "$45",
        sizes: ML,
        tag: "Set",
        image: "/images/products/Outfit_Styles_037.jpeg",
      },
      {
        id: "ws38",
        title: "Brown Outing Jacket",
        price: "$45",
        sizes: ML,
        tag: "Set",
        image: "/images/products/Outfit_Styles_038.jpeg",
      },
      {
        id: "ws41",
        title: "Yellow-Gold Jumpsuit",
        price: "$65",
        sizes: ML,
        tag: "Set",
        image: "/images/products/Outfit_Styles_041.jpeg",
      },
      {
        id: "ws42",
        title: "Dress to Impress White Set Pant",
        sizes: ML,
        tag: "Set",
        image: "/images/products/Outfit_Styles_042.jpeg",
      },
      {
        id: "ws48",
        title: "Multicolor Metallic Party Set",
        sizes: ML,
        tag: "Party",
        image: "/images/products/Outfit_Styles_048.jpeg",
      },
      {
        id: "ws49",
        title: "Multicolor Metallic Party Set",
        sizes: ML,
        tag: "Party",
        image: "/images/products/Outfit_Styles_049.jpeg",
      },
      {
        id: "ws63",
        title: "Beaded Black Hoodie Shirt",
        price: "$65",
        sizes: ["M"],
        tag: "Top",
        image: "/images/products/Outfit_Styles_063.jpeg",
      },
    ],
  },

  "occasion-wear": {
    title: "Occasion Wear",
    intro: "Statement pieces designed for weddings, celebrations, and grand entrances.",
    heroImage: "/images/women/occasion-wear.png",
    products: [
      {
        id: "wo3",
        title: "Sassy Military Color Jumpsuit",
        price: "$55",
        sizes: ML,
        tag: "Occasion",
        image: "/images/products/Outfit_Styles_003.jpeg",
      },
      {
        id: "wo11",
        title: "Classic Jumpsuit",
        price: "$55",
        sizes: ML,
        tag: "Occasion",
        image: "/images/products/Outfit_Styles_011.jpeg",
      },
      {
        id: "wo13",
        title: "Classic Long Jumpsuit",
        price: "$55",
        sizes: ML,
        tag: "Occasion",
        image: "/images/products/Outfit_Styles_013.jpeg",
      },
      {
        id: "wo39",
        title: "Gold Dress to Party Jumpsuit",
        price: "$60",
        sizes: ML,
        tag: "Occasion",
        image: "/images/products/Outfit_Styles_039.jpeg",
      },
      {
        id: "wo40",
        title: "Multicolor Front Part Dress",
        price: "$55",
        sizes: ML,
        tag: "Occasion",
        image: "/images/products/Outfit_Styles_040.jpeg",
      },
      {
        id: "wo52",
        title: "Purple 2 Set Skirt",
        price: "$35",
        sizes: ML,
        tag: "Occasion",
        image: "/images/products/Outfit_Styles_052.jpeg",
      },
      {
        id: "wo53",
        title: "Purple 2 Set Skirt",
        price: "$35",
        sizes: ML,
        tag: "Occasion",
        image: "/images/products/Outfit_Styles_053.jpeg",
      },
      {
        id: "wo54",
        title: "African Style Jumpsuit",
        price: "$65",
        sizes: ML,
        tag: "Occasion",
        image: "/images/products/Outfit_Styles_054.jpeg",
      },
      {
        id: "wo55",
        title: "Pink African Dress",
        price: "$80",
        sizes: ONE_SIZE,
        tag: "African",
        image: "/images/products/Outfit_Styles_055.jpeg",
      },
      {
        id: "wo56",
        title: "African Embroidered Jacket",
        price: "$110",
        sizes: ONE_SIZE,
        tag: "African",
        image: "/images/products/Outfit_Styles_056.jpeg",
      },
      {
        id: "wo58",
        title: "Blue/Black African Dress",
        price: "$80",
        sizes: ONE_SIZE,
        tag: "African",
        image: "/images/products/Outfit_Styles_058.jpeg",
      },
      {
        id: "wo64",
        title: "African Embroidered Jacket",
        price: "$110",
        sizes: ONE_SIZE,
        tag: "African",
        image: "/images/products/Outfit_Styles_064.jpeg",
      },
    ],
  },

  accessories: {
    title: "Accessories",
    intro: "Elegant finishing details that sharpen and complete the full look.",
    heroImage:
      "/images/products/jewelry/jewelry-sets/Jewelries_Samples2_016.jpeg",
    products: [],
  },
};

export const menCategoryPages: Record<string, CategoryPage> = {
  "native-wear": {
    title: "Native Wear",
    intro: "Traditional looks with refined tailoring and strong presence.",
    heroImage: "/images/men/native-wear.png",
    products: [
      {
        id: "mn1",
        title: "Modern Monarch Native Set",
        price: "$145",
        sizes: ML,
        tag: "Featured",
        image: "/images/products/modern-monarch-native-set.png",
      },
      {
        id: "mn2",
        title: "Classic Men Native Set",
        price: "$220",
        sizes: ML,
        tag: "Native",
        image: "/images/products/classic-men-native-set.png",
      },
      {
        id: "mn32",
        title: "Outfit Styles 032",
        price: "$75",
        sizes: ML,
        tag: "Native",
        image: "/images/products/Outfit_Styles_032.jpeg",
      },
      {
        id: "mn67",
        title: "Outfit Styles 067",
        price: "$130",
        sizes: ML,
        tag: "Native",
        image: "/images/products/Outfit_Styles_067.jpeg",
      },
      {
        id: "mn70",
        title: "Outfit Styles 070",
        price: "$180",
        sizes: ML,
        tag: "Native",
        image: "/images/products/Outfit_Styles_070.jpeg",
      },
    ],
  },

  "senator-sets": {
    title: "Senator Sets",
    intro: "Modern, clean lines with premium structure for everyday confidence.",
    heroImage: "/images/men/senator-sets.png",
    products: [
      {
        id: "ms1",
        title: "Classic Senator Statement",
        price: "$145",
        sizes: ML,
        tag: "Featured",
        image: "/images/products/classic-senator-statement.png",
      },
      {
        id: "ms2",
        title: "Modern Monarch Men Set",
        price: "$145",
        sizes: ML,
        tag: "Featured",
        image: "/images/products/modern-monarch-men-set.png",
      },
      {
        id: "ms31",
        title: "Outfit Styles 031",
        price: "$95",
        sizes: ML,
        tag: "Senator",
        image: "/images/products/Outfit_Styles_031.jpeg",
      },
      {
        id: "ms33",
        title: "Outfit Styles 033",
        price: "$110",
        sizes: ML,
        tag: "Senator",
        image: "/images/products/Outfit_Styles_033.jpeg",
      },
      {
        id: "ms68",
        title: "Outfit Styles 068",
        price: "$98",
        sizes: ML,
        tag: "Senator",
        image: "/images/products/Outfit_Styles_068.jpeg",
      },
      {
        id: "ms69",
        title: "Outfit Styles 069",
        price: "$145",
        sizes: ML,
        tag: "Senator",
        image: "/images/products/Outfit_Styles_069.jpeg",
      },
    ],
  },

  agbada: {
    title: "Agbada",
    intro: "Grand occasion dressing with elegance, dignity, and visual power.",
    heroImage: "/images/men/agbada.png",
    products: [
      {
        id: "ma1",
        title: "Ivory Prestige Agbada",
        price: "$175",
        sizes: ML,
        tag: "Featured",
        image: "/images/products/ivory-prestige-agbada.png",
      },
      {
        id: "ma2",
        title: "Ivory Occasion Agbada",
        price: "$180",
        sizes: ML,
        tag: "Agbada",
        image: "/images/products/ivory-occasion-agbada.png",
      },
      {
        id: "ma29",
        title: "Outfit Styles 029",
        price: "$95",
        sizes: ML,
        tag: "Agbada",
        image: "/images/products/Outfit_Styles_029.jpeg",
      },
      {
        id: "ma30",
        title: "Outfit Styles 030",
        price: "$110",
        sizes: ML,
        tag: "Agbada",
        image: "/images/products/Outfit_Styles_030.jpeg",
      },
    ],
  },

  accessories: {
    title: "Accessories",
    intro: "Sharp details that complete the full look without excess.",
    heroImage: "/images/products/m-hat-1.jpeg",
    products: [],
  },
};